print("Hello from master branch")
print("I'm 23 years old")
print("Hello from feature1")
print("This file was changed in feature1")
print("This is test.py from feature2")
print("I am practicing Git branches")
print("I like listening to Sinhala classical songs")
